DO $block$
DECLARE
  v_creator_id uuid;
  v_spec jsonb;
  v_listing_id uuid;
  v_specs jsonb := $json$
  [
    {"title": "Coastal Storybook Landscape — House Above the Sea","description": "A cinematic vertical landscape of an old hilltop house above the sea, rendered with soft pastel light, green-yellow fields, blue sky, and drifting white clouds.","aspect_ratio": "9:16","image_type": "Illustration","style_tags": ["coastal", "storybook", "house", "pastel", "cinematic", "landscape", "midjourney", "pickture-demo"],"usage_rights": "personal","price_cents": 1200,"consistency_score": 87,"full_prompt": "In the distance, there is an old house on top of grassy hill overlooking sea, blue sky and white clouds, by Atey Ghailan, Ryo Takemasa, Hayao Miyazaki, Makoto Shinkai, Tatsuro Kiuchi, Ilya Kuvshinov, Makato Harimatsu, Studio Ghibli, green yellow color palette, natural light, pastel colors, wide shot, cinematic, ultra realistic --ar 9:16 --raw --profile lezo2k8 5fbo5aq --stylize 1000 --v 7","negative_prompt": "","settings": {"stylize": 1000,"seed_policy": "Keep personalization profiles lezo2k8 and 5fbo5aq unchanged for the closest repeatability.","style_reference": "No --sref value; the recipe relies on the named visual references and personalization profiles.","aspect_ratio": "9:16","raw": true},"usage_notes": "Personal-use listing because the recipe names artists and Studio Ghibli. Preserve --raw, both profile codes, --stylize 1000, and --v 7 when changing the house or coastline."},
    {"title": "Organic Land-Art Architecture — Yellow Pathways","description": "A surreal architectural landscape with smooth yellow pathways, rounded green hills, a lone figure, and a serene blue sky in a clean organic composition.","aspect_ratio": "2:3","image_type": "Architecture","style_tags": ["architecture", "organic", "land-art", "surreal", "minimal", "green", "yellow", "pickture-demo"],"usage_rights": "commercial","price_cents": 1500,"consistency_score": 88,"full_prompt": "An avant gardist organic landscape with smooth white pathways curving between large rounded green architectural hills, minimalist composition, man in yellow suit walking through, strong contrast between greenery and clean yellow surfaces, serene blue sky, cinematic perspective, architectural photography, inspired by organic design and land art, 85mm lens, ultra-realistic lighting, modern and surreal atmosphere --ar 2:3 --raw --v 7","negative_prompt": "","settings": {"seed_policy": "Use a fixed seed for a series and change only one pathway or hill detail per variation.","style_reference": "No style reference supplied.","aspect_ratio": "2:3","raw": true},"usage_notes": "Keep the 85mm lens, blue-sky lighting, lone yellow-suited figure, --raw, and --v 7 fixed. Change one architectural form at a time."},
    {"title": "Lifestyle Portrait — Morning Latte","description": "Full-height natural-light lifestyle portrait on a warm beige backdrop, featuring a model holding a latte with clean editorial styling and realistic skin detail.","aspect_ratio": "9:16","image_type": "Portrait","style_tags": ["portrait", "lifestyle", "latte", "model", "beige", "natural-light", "editorial", "pickture-demo"],"usage_rights": "personal","price_cents": 1400,"consistency_score": 87,"full_prompt": "A Russian model with clear skin holds a latte cup in her hand. She stands with her eyes open on a beige background. The photo was taken in high resolution, high quality and with high detail, in natural light and in full height, which demonstrates the natural features of the model by Guy Aroch --ar 9:16 --profile et4t3gm 3rxvsfr na8aiho xzfnyy1 --v 7","negative_prompt": "","settings": {"seed_policy": "Keep profiles et4t3gm, 3rxvsfr, na8aiho, and xzfnyy1 together; use a fixed seed for wardrobe variations.","style_reference": "No --sref value; personalization profiles control the visual treatment.","aspect_ratio": "9:16","raw": false},"usage_notes": "Personal-use listing because the recipe names a photographer. Preserve the four profile codes, full-height framing, beige background, natural light, and --v 7."},
    {"title": "Parametric Residence — Angular Urban Landmark","description": "Award-style vertical architecture photography of a bold parametric residential building with angular geometry and a refined urban context.","aspect_ratio": "9:16","image_type": "Architecture","style_tags": ["architecture", "parametric", "residential", "urban", "angular", "editorial", "award", "pickture-demo"],"usage_rights": "personal","price_cents": 1800,"consistency_score": 88,"full_prompt": "ArchiDaily magazine award-winning photography luxury parametric architecture residential building angular bold design urban context --ar 9:16 --raw --sref 975865617 --profile 92ihohk 2ld2j4p --stylize 1000 --v 7","negative_prompt": "","settings": {"stylize": 1000,"seed_policy": "Keep personalization profiles 92ihohk and 2ld2j4p unchanged.","style_reference": "Use --sref 975865617 exactly as supplied.","aspect_ratio": "9:16","raw": true},"usage_notes": "Personal-use listing because the recipe invokes a publication identity and saved style reference. Preserve --sref 975865617, both profiles, --stylize 1000, and --raw."},
    {"title": "Beauty Editorial — Shell and Sea","description": "An airy seaside beauty portrait with a blonde woman holding a large seashell over one eye, soft natural light, and intimate mid-body framing.","aspect_ratio": "3:4","image_type": "Portrait","style_tags": ["beauty", "portrait", "seashell", "sea", "airy", "blonde", "editorial", "pickture-demo"],"usage_rights": "commercial","price_cents": 1400,"consistency_score": 88,"full_prompt": "Middle body portrait of a woman holding a large seashell covering one eye, shell touching the face, hand gently holding it, face filling most of the frame. Airy light aesthetic. Blonde hair. Sea background --ar 3:4 --profile 6bex1oz fxum4rs ss2sgva jdftqub ydpuj7w gub2puj n3todad oze7qog 2ld2j4p --v 7","negative_prompt": "","settings": {"seed_policy": "Keep all nine personalization profiles together and use a fixed seed for expression or shell variations.","style_reference": "No --sref value; the profile set controls the treatment.","aspect_ratio": "3:4","raw": false},"usage_notes": "Keep the shell touching the face, one-eye coverage, mid-body crop, airy light, sea background, profile sequence, and --v 7 unchanged."},
    {"title": "Beverage Campaign — Iced Matcha","description": "Hyper-realistic close-up beverage photography of a hand holding an iced matcha latte against a clean beige background with crisp commercial detail.","aspect_ratio": "3:4","image_type": "Food","style_tags": ["matcha", "beverage", "hand", "commercial", "beige", "photorealistic", "close-up", "pickture-demo"],"usage_rights": "commercial","price_cents": 1100,"consistency_score": 87,"full_prompt": "a black woman's hand holding an iced matcha latte in a plastic cup with a straw\" on it, against a beige background, hyper-realistic photography, highly detailed and intricate. --ar 3:4 --raw --profile oqst3mx 2n32e8s --stylize 50 --v 7","negative_prompt": "","settings": {"stylize": 50,"seed_policy": "Keep profiles oqst3mx and 2n32e8s together for campaign consistency.","style_reference": "No --sref value supplied.","aspect_ratio": "3:4","raw": true},"usage_notes": "Preserve the hand-and-cup composition, beige background, both profiles, --stylize 50, --raw, and --v 7. Replace only the beverage color or garnish."},
    {"title": "Minimal Landscape — Red House Reflection","description": "A tranquil vertical landscape of simple red houses, rolling hills, misty mountains, and a clear lake reflection in a restrained blue-gray palette.","aspect_ratio": "9:16","image_type": "Landscape","style_tags": ["minimal", "landscape", "red-house", "lake", "reflection", "mountains", "tranquil", "pickture-demo"],"usage_rights": "commercial","price_cents": 1200,"consistency_score": 87,"full_prompt": "Minimalist, clean lines, mountains and houses, calm lake water, distant view, sky blue background color, light gray, minimalist style, ethereal landscapes, tranquil scenery, simple red house, minimalistic composition, clear reflection on the surface of the sea. The picture is composed in high definition photography style. A minimalist scene with red wooden buildings on top of rolling hills, foggy mountain peaks. --ar 9:16 --raw --profile 2ld2j4p --v 7","negative_prompt": "","settings": {"seed_policy": "Keep profile 2ld2j4p and use a fixed seed for a cohesive landscape series.","style_reference": "No --sref value supplied.","aspect_ratio": "9:16","raw": true},"usage_notes": "Keep the red buildings, blue-gray palette, calm reflection, distant foggy peaks, --raw, profile 2ld2j4p, and --v 7 fixed."},
    {"title": "Sports Magazine Cover — Messi 10","description": "A premium vertical football cover featuring Lionel Messi mid-strike, bold layered number-ten typography, Argentina colors, and a dramatic dust burst.","aspect_ratio": "51:91","image_type": "Sports","style_tags": ["football", "messi", "argentina", "magazine-cover", "typography", "sports", "cinematic", "pickture-demo"],"usage_rights": "personal","price_cents": 1400,"consistency_score": 88,"full_prompt": "Lionel Messi in Argentina national team kit mid-strike with giant bold number \"10\" behind him in layered typography, white and sky blue palette, dust and particle explosion from ground, crisp shadows, minimalistic premium layout, luxury sports magazine cover style, text \"MESSI 10\" in bold elegant serif font, 8K ultra detailed, cinematic grading --ar 51:91 --profile 2ld2j4p --v 7","negative_prompt": "","settings": {"seed_policy": "Keep profile 2ld2j4p; use a fixed seed if generating alternate poses or cover layouts.","style_reference": "No --sref value supplied.","aspect_ratio": "51:91","raw": false},"usage_notes": "Personal-use only because the recipe uses a real athlete, national-team identity, and name. Preserve exact quoted text, profile 2ld2j4p, and --v 7."},
    {"title": "Cinematic Character Poster — Moon Knight Astral Form","description": "A vertical superhero poster with a white-suited figure, offset golden astral form, sacred geometric moon portal, Egyptian symbols, and a reflective silver floor.","aspect_ratio": "9:16","image_type": "Illustration","style_tags": ["moon-knight", "superhero", "astral", "egyptian", "poster", "cinematic", "sacred-geometry", "pickture-demo"],"usage_rights": "personal","price_cents": 1600,"consistency_score": 88,"full_prompt": "Moon Knight standing facing camera in his white suit, his golden astral form slightly displaced outward his Mr. Knight physical body crisp and sharp while a glowing gold astral version of himself extends just beyond his silhouette. Behind him: an enormous circular Khonshu-moon aura disc of silver and gold sacred geometry glows like a portal, ancient Egyptian hieroglyphs orbiting the ring. Ground: reflective silver surface mirroring the entire disc. IMAX 70mm, 8K, Marvel Studios. --ar 9:16 --profile 2ld2j4p --v 7","negative_prompt": "","settings": {"seed_policy": "Keep profile 2ld2j4p and use a fixed seed for alternate astral offsets.","style_reference": "No --sref value supplied.","aspect_ratio": "9:16","raw": false},"usage_notes": "Personal-use only because the recipe uses protected character and studio properties. Preserve the portal, astral offset, reflective floor, profile 2ld2j4p, and --v 7."},
    {"title": "Cosmic Road Film Still — Galactic Wheatfield","description": "A lone car crosses an endless dirt road through golden wheat fields beneath colossal spiral-galaxy arms, combining rural warmth with epic cosmic scale.","aspect_ratio": "9:16","image_type": "Cinematic","style_tags": ["cosmic", "car", "wheatfield", "galaxy", "road", "cinematic", "science-fiction", "pickture-demo"],"usage_rights": "personal","price_cents": 1500,"consistency_score": 88,"full_prompt": "Lone car driving down endless dirt road through golden wheat fields, massive spiral galaxy arms swirling overhead like cosmic tornado, warm amber light from galactic core illuminating cornfield landscape, vehicle's taillights creating red streak against billion-star backdrop, IMAX 70mm grain texture, Christopher Nolan's rural cosmic poetry --ar 9:16 --profile 2ld2j4p --v 7","negative_prompt": "","settings": {"seed_policy": "Keep profile 2ld2j4p and use a fixed seed to preserve the road, car, and galaxy relationship.","style_reference": "No --sref value supplied.","aspect_ratio": "9:16","raw": false},"usage_notes": "Personal-use listing because the recipe names a living filmmaker. Preserve the lone-car count, wheatfield road, galaxy-arm structure, profile 2ld2j4p, and --v 7."}
  ]
  $json$::jsonb;
BEGIN
  SELECT creator_id INTO v_creator_id
    FROM public.listings
   WHERE 'pickture-demo' = ANY(style_tags)
   ORDER BY created_at LIMIT 1;
  IF v_creator_id IS NULL THEN RAISE EXCEPTION 'No existing Pickture demo creator was found'; END IF;

  FOR v_spec IN SELECT * FROM jsonb_array_elements(v_specs) LOOP
    SELECT id INTO v_listing_id FROM public.listings
     WHERE creator_id = v_creator_id AND title = v_spec->>'title' LIMIT 1;

    IF v_listing_id IS NULL THEN
      INSERT INTO public.listings (
        creator_id, title, description, model, model_version, aspect_ratio,
        image_type, style_tags, usage_rights, price_cents,
        partial_prompt_preview, consistency_score, status
      ) VALUES (
        v_creator_id, v_spec->>'title', v_spec->>'description', 'midjourney-v7', 'v7',
        v_spec->>'aspect_ratio', v_spec->>'image_type',
        ARRAY(SELECT jsonb_array_elements_text(v_spec->'style_tags')),
        (v_spec->>'usage_rights')::public.usage_rights,
        (v_spec->>'price_cents')::int, '', (v_spec->>'consistency_score')::int, 'published'
      ) RETURNING id INTO v_listing_id;
    ELSE
      UPDATE public.listings
         SET description = v_spec->>'description', model = 'midjourney-v7', model_version = 'v7',
             aspect_ratio = v_spec->>'aspect_ratio', image_type = v_spec->>'image_type',
             style_tags = ARRAY(SELECT jsonb_array_elements_text(v_spec->'style_tags')),
             usage_rights = (v_spec->>'usage_rights')::public.usage_rights,
             price_cents = (v_spec->>'price_cents')::int, partial_prompt_preview = '',
             consistency_score = (v_spec->>'consistency_score')::int, status = 'published'
       WHERE id = v_listing_id;
    END IF;

    INSERT INTO public.recipe_secrets (listing_id, full_prompt, negative_prompt, settings, usage_notes)
    VALUES (v_listing_id, v_spec->>'full_prompt', v_spec->>'negative_prompt', v_spec->'settings', v_spec->>'usage_notes')
    ON CONFLICT (listing_id) DO UPDATE SET
      full_prompt = EXCLUDED.full_prompt,
      negative_prompt = EXCLUDED.negative_prompt,
      settings = EXCLUDED.settings,
      usage_notes = EXCLUDED.usage_notes;
  END LOOP;
END $block$;